#make file for c

CC = gcc

SOURCES = \
main.cpp \
boundary_condition.cpp \
initial_condition.cpp \
reconstruction.cpp \
riemann.cpp \
time_integral.cpp \
calculation.cpp \
plot.cpp \
write.cpp

main :
	$(CC) $(SOURCES) -lm

